import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Nav, NavLink } from "@/components/Nav";
import type { ReactNode } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav>
          <NavLink href="/about">About Us</NavLink>
          <NavLink href="/breweries">Breweries</NavLink>
          <NavLink href="/smash">JBA SMaSH</NavLink>
        </Nav>
        <div className="p-2 m-1">{children}</div>
      </body>
    </html>
  );
}
